### ISSUE TITLE
ELM-v3.0.0 fails to import in Protege and Topbraid Composer

### ISSUE THREAD

**Issue by skontopo** [european-commission-empl/European-Learning-Model#91]
[ELM-v3.0.0](https://raw.githubusercontent.com/european-commission-empl/European-Learning-Model/master/rdf/ontology/ELM-v3.0.0.ttl) unfortunately cannot be imported in Protege or Topbraid Composer. 

Error generated by Protege:
`ERROR  15:09:28  An error occurred whilst extracting the Ontology Id from the imported ontology: {}
java.lang.NullPointerException: null
	at org.protege.editor.owl.model.repository.MasterOntologyIDExtractor.getOntologyId(MasterOntologyIDExtractor.java:27) ~[protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.checkImport(AnticipateOntologyIdPage.java:109) [protege-editor-owl.jar:na]
	at org.protege.editor.owl.ui.ontology.imports.wizard.page.AnticipateOntologyIdPage.lambda$new$0(AnticipateOntologyIdPage.java:44) [protege-editor-owl.jar:na]
	at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]`

Error generated by Topbraid Composer:
`java.lang.reflect.InvocationTargetException
	at org.topbraidcomposer.navigation.imports.actions.ImportURLAction$1.run(ImportURLAction.java:102)
	at org.topbraidcomposer.core.util.ThreadUtil$1$1.run(ThreadUtil.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Error loading graph null
	at org.topbraid.core.io.IO.loadAndRegister(IO.java:353)
	at org.topbraid.core.io.IO.load(IO.java:299)
	at org.topbraid.core.io.IO.load(IO.java:281)
	at org.topbraidcomposer.core.io.TBCIO.loadModel(TBCIO.java:303)
	at org.topbraidcomposer.core.models.Imports.getImportedModel(Imports.java:120)
	at org.topbraidcomposer.core.models.Imports.addImport(Imports.java:106)
	at org.topbraidcomposer.navigation.imports.actions.ImportURLAction$1.run(ImportURLAction.java:98)
	... 2 more
Caused by: java.io.IOException: Unexpected graph source problem for URI https://raw.githubusercontent.com/european-commission-empl/European-Learning-Model/master/rdf/ontology/ELM-v3.0.0.ttl
	at org.topbraid.core.io.IO.loadAndRegister(IO.java:333)
	... 8 more
Root exception:
java.io.IOException: Error loading graph null
	at org.topbraid.core.io.IO.loadAndRegister(IO.java:353)
	at org.topbraid.core.io.IO.load(IO.java:299)
	at org.topbraid.core.io.IO.load(IO.java:281)
	at org.topbraidcomposer.core.io.TBCIO.loadModel(TBCIO.java:303)
	at org.topbraidcomposer.core.models.Imports.getImportedModel(Imports.java:120)
	at org.topbraidcomposer.core.models.Imports.addImport(Imports.java:106)
	at org.topbraidcomposer.navigation.imports.actions.ImportURLAction$1.run(ImportURLAction.java:98)
	at org.topbraidcomposer.core.util.ThreadUtil$1$1.run(ThreadUtil.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Unexpected graph source problem for URI https://raw.githubusercontent.com/european-commission-empl/European-Learning-Model/master/rdf/ontology/ELM-v3.0.0.ttl
	at org.topbraid.core.io.IO.loadAndRegister(IO.java:333)
	... 8 more`

**Comment by anthonycamilleri** [comment]
@skontopo this is due to the pending publication of the files which are referenced with the EU Publications office. This will happen in the next 2-3 weeks, and then everything should run fine without intervention.

**Comment by skontopo** [comment]
@anthonycamilleri many thanks for the heads-up. Could you please post a message here once this is done?

**Comment by anthonycamilleri** [comment]
@skontopo this should now be resolved.
